### ISSUE TITLE
Any reference implementations of BEAT3?

### ISSUE THREAD

**Issue by Qix-** [fififish/beat#1]
Hi there, do you know of any reference implementations of BEAT3? I can't seem to find anything other than what's mentioned in the seminal paper.

Thanks!

**Comment by fififish** [comment]
ah, I'm too lazy on this. Haven't cleaned up the codebase and upload it yet...will work on it soon.

**Comment by Qix-** [comment]
Looking forward :) Thanks so much for the work on this stuff!

**Comment by ProjectInitiative** [comment]
I am also interested in this project!

**Comment by fififish** [comment]
I checked the repo a while ago and realized that there was some segmentation issue due to the lack of support of python2 libraries. It might only work on certain old linux os. I'll double check later (when I finish a couple of things).
